<a href="https://colab.research.google.com/github/a-taylor1/DATA450_Team5/blob/main/Assignment11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)

%matplotlib inline

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/eitellauria/datafiles/main/ShoppingData.csv")

In [ ]:
itemsets = apriori(data, min_support=0.1, use_colnames=True)
itemsets

     support                                        itemsets
0   0.492366                                     (ReadyMade)
1   0.402036                                   (FrozenFoods)
2   0.394402                                       (Alcohol)
3   0.188295                                          (Milk)
4   0.428753                                   (BakeryGoods)
5   0.474555                                        (Snacks)
6   0.455471                                   (TinnedGoods)
7   0.211196                        (ReadyMade, FrozenFoods)
8   0.212468                            (Alcohol, ReadyMade)
9   0.133588                               (ReadyMade, Milk)
10  0.255725                        (BakeryGoods, ReadyMade)
11  0.244275                             (ReadyMade, Snacks)
12  0.216285                        (ReadyMade, TinnedGoods)
13  0.230280                          (Alcohol, FrozenFoods)
14  0.108142                             (FrozenFoods, Milk)
15  0.221374                      (BakeryGoods, FrozenFoods)
16  0.213740                           (FrozenFoods, Snacks)
17  0.207379                      (FrozenFoods, TinnedGoods)
18  0.114504                                 (Alcohol, Milk)
19  0.215013                          (Alcohol, BakeryGoods)
20  0.218830                               (Alcohol, Snacks)
21  0.173028                          (Alcohol, TinnedGoods)
22  0.139949                             (BakeryGoods, Milk)
23  0.124682                                  (Milk, Snacks)
24  0.127226                             (TinnedGoods, Milk)
25  0.232824                           (BakeryGoods, Snacks)
26  0.227735                      (BakeryGoods, TinnedGoods)
27  0.223919                           (TinnedGoods, Snacks)
28  0.143766               (Alcohol, ReadyMade, FrozenFoods)
29  0.138677           (BakeryGoods, ReadyMade, FrozenFoods)
30  0.127226                (ReadyMade, FrozenFoods, Snacks)
31  0.125954           (ReadyMade, TinnedGoods, FrozenFoods)
32  0.146310               (Alcohol, BakeryGoods, ReadyMade)
33  0.134860                    (Alcohol, ReadyMade, Snacks)
34  0.120865               (Alcohol, ReadyMade, TinnedGoods)
35  0.105598                  (BakeryGoods, ReadyMade, Milk)
36  0.147583                (BakeryGoods, ReadyMade, Snacks)
37  0.146310           (BakeryGoods, ReadyMade, TinnedGoods)
38  0.138677                (ReadyMade, TinnedGoods, Snacks)
39  0.142494             (Alcohol, BakeryGoods, FrozenFoods)
40  0.142494                  (Alcohol, FrozenFoods, Snacks)
41  0.120865             (Alcohol, FrozenFoods, TinnedGoods)
42  0.136132              (BakeryGoods, FrozenFoods, Snacks)
43  0.148855         (BakeryGoods, FrozenFoods, TinnedGoods)
44  0.114504              (FrozenFoods, TinnedGoods, Snacks)
45  0.137405                  (Alcohol, BakeryGoods, Snacks)
46  0.123410             (Alcohol, BakeryGoods, TinnedGoods)
47  0.115776                  (Alcohol, TinnedGoods, Snacks)
48  0.100509                (BakeryGoods, TinnedGoods, Milk)
49  0.137405              (BakeryGoods, TinnedGoods, Snacks)
50  0.104326  (Alcohol, BakeryGoods, ReadyMade, FrozenFoods)
51  0.101781       (Alcohol, BakeryGoods, ReadyMade, Snacks)
52  0.100509  (Alcohol, BakeryGoods, ReadyMade, TinnedGoods)

In [ ]:
rules = association_rules(itemsets, metric='confidence', min_threshold=0.8)
rules = rules[[len(c) <= 3 for c in rules.antecedents]]
rules = rules[[c >= 1.5 for c in rules.lift]]
rules.drop(columns=['antecedent support', 'consequent support', 'conviction', 'leverage', 'zhangs_metric', 'representativity','jaccard','certainty', 'kulczynski'])

,antecedents,consequents,support,confidence,lift
0,"(Alcohol, BakeryGoods, TinnedGoods)",(ReadyMade),0.100509,0.814433,1.654120
1,"(Alcohol, ReadyMade, TinnedGoods)",(BakeryGoods),0.100509,0.831579,1.939528

1. If a customer purchases alcohol, baked goods, and tinned goods, we are 81% confident that they will also purchase Ready Made.
2. If a customer purchase alcohol, Ready Made, and tinned goods, we are 83% confident that they will also purchase baked goods.